import { Schema } from "effect"
import { Span } from "@/diagnostic/span";

export const TokenKind = Schema.Literal(
    "LeftParen",
    "RightParen",
    "LeftBrace",
    "RightBrace",
    "LeftBracket",
    "RightBracket",
    "Comma",
    "Dot",
    "DotDot",
    "DotDotEqual",
    "Semicolon",
    "Colon",
    "DoubleColon",
    "Arrow",
    "FatArrow",
    "Plus",
    "PlusEqual",
    "Minus",
    "MinusEqual",
    "Star",
    "StarEqual",
    "StarStar",
    "Slash",
    "SlashEqual",
    "Percent",
    "PercentEqual",
    "Bang",
    "BangEqual",
    "Equal",
    "EqualEqual",
    "Less",
    "LessEqual",
    "LessLess",
    "Greater",
    "GreaterEqual",
    "GreaterGreater",
    "Ampersand",
    "AmpersandAmpersand",
    "Pipe",
    "PipePipe",
    "Caret",
    "Tilde",
    "Question",
    "At",
    "Hash",
    "Let",
    "Mut",
    "Fn",
    "Return",
    "If",
    "Else",
    "While",
    "For",
    "In",
    "Break",
    "Continue",
    "True",
    "False",
    "Nil",
    "And",
    "Or",
    "Not",
    "Type",
    "Struct",
    "Enum",
    "Match",
    "Import",
    "Export",
    "As",
    "Identifier",
    "IntLiteral",
    "FloatLiteral",
    "StringLiteral",
    "Eof",
)
export type TokenKind = typeof TokenKind.Type

export class Token extends Schema.Class<Token>("Token")({
    kind: TokenKind,
    lexeme: Schema.String,
    span: Schema.instanceOf(Span),
}) { }
